### ISSUE TITLE
Add an endpoint to list images for a day

### ISSUE THREAD

**Issue by mdaffin** [mdaffin/timelapse#3]
```
/api/images/{day}
```

There should be a way to list all available images for a given day. Once #1 is done this should be as simple as using [read_dir](https://doc.rust-lang.org/std/fs/fn.read_dir.html) on one of day directories, formatting the results into a struct and [serialising](https://serde.rs/) the results.

**Comment by ebleb** [comment]
Do you want the response to resemble a file system with clickable links or to only be a list of file names?

**Comment by mdaffin** [comment]
The response should be json - so nothing _clickable_ but it should include the URL to the images so the front-end knows where to fetch them from. Something like:

```
[
  { "src": "/images/2020-10-01/17:01:08+01:00.png" },
  { "src": "/images/2020-10-01/17:01:08+01:00.png" },
  { "src": "/images/2020-10-01/17:01:08+01:00.png" },
  { "src": "/images/2020-10-01/17:01:08+01:00.png" }
]
```
